# Generated by Django 4.1.7 on 2023-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0003_alter_doctor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(max_length=400),
        ),
    ]
